# Generated by Django 5.0.2 on 2025-05-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Startup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="startups/")),
                ("team_size", models.PositiveIntegerField()),
                ("funding", models.CharField(max_length=50)),
                ("description", models.TextField()),
                (
                    "industry",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated industry tags, e.g., AI, Fintech, Medtech",
                        max_length=255,
                    ),
                ),
                ("country", models.CharField(max_length=20)),
                (
                    "registrationDate",
                    models.CharField(
                        help_text="Enter in MM/YYYY format", max_length=10
                    ),
                ),
            ],
        ),
    ]
