# Generated by Django 4.2.7 on 2025-06-16 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_lesson_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='duration',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
    ]
