# Generated by Django 5.0.2 on 2025-07-26 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0004_lesson_duration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personalizedsession",
            name="notes",
        ),
        migrations.AddField(
            model_name="personalizedsession",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Describe what you want to learn or discuss in this session",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="personalizedsession",
            name="topic",
            field=models.CharField(
                blank=True,
                help_text="Topic or subject for the personalized session",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="duration",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="personalizedsession",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="courses.course",
            ),
        ),
    ]
